// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package es.sendit2us.wastetracker.client.blackberry.rest;


public class AssignResponse {
    protected PickupHeader[] assigned;
    protected java.lang.String message;
    
    public AssignResponse() {
    }
    
    public AssignResponse(PickupHeader[] assigned, java.lang.String message) {
        this.assigned = assigned;
        this.message = message;
    }
    
    public PickupHeader[] getAssigned() {
        return assigned;
    }
    
    public void setAssigned(PickupHeader[] assigned) {
        this.assigned = assigned;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
}
