// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package es.sendit2us.wastetracker.client.blackberry.rest;

import net.rim.device.api.util.Persistable;

public abstract class MasterDataEntity implements Persistable {
	protected java.lang.String code;
	protected java.lang.String description;
	protected int id;
	
	protected MasterDataEntity() {
	}

	protected MasterDataEntity(java.lang.String code, java.lang.String description, int id) {
		this.code = code;
		this.description = description;
		this.id = id;
	}

	public java.lang.String getCode() {
		return code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.String getDescription() {
		return description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public MasterDataEntity clone() {
		MasterDataEntity newOne = null;
		try {
			newOne = (MasterDataEntity) this.getClass().newInstance();
			System.out.println("Clase: " + newOne.getClass());
			newOne.id = this.id;
			newOne.code = this.code;
			newOne.description = this.description;
		} catch (InstantiationException e) {
			System.out.println(e);
		} catch (IllegalAccessException e) {
			System.out.println(e);
		}
		return newOne;
	}
	
	public abstract MasterDataEntity[] getArray(int numElems);
}