// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package es.sendit2us.wastetracker.client.blackberry.rest;

import net.rim.device.api.util.Persistable;

public class PickupDetail implements Persistable {
	
	public static final long serialVersionUID = 2148075554167861369L;
	
	protected java.lang.String categoryCode;
	protected java.lang.String categoryDesc;
	protected java.lang.String containerCode;
	protected java.lang.String containerDescr;
	protected java.lang.String familyCode;
	protected java.lang.String familyDesc;
	protected int id;
	protected int state;
	protected java.lang.String usageCode;
	protected java.lang.String usageDesc;
	protected java.lang.String barcode;

	public PickupDetail() {
	}

	public PickupDetail(java.lang.String categoryCode, java.lang.String categoryDesc, java.lang.String containerCode,
			java.lang.String containerDescr, java.lang.String familyCode, java.lang.String familyDesc, int id, int state,
			java.lang.String usageCode, java.lang.String usageDesc, String barcode) {
		this.categoryCode = categoryCode;
		this.categoryDesc = categoryDesc;
		this.containerCode = containerCode;
		this.containerDescr = containerDescr;
		this.familyCode = familyCode;
		this.familyDesc = familyDesc;
		this.id = id;
		this.state = state;
		this.usageCode = usageCode;
		this.usageDesc = usageDesc;
		this.barcode = barcode;
	}

	public java.lang.String getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(java.lang.String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public java.lang.String getCategoryDesc() {
		return categoryDesc;
	}

	public void setCategoryDesc(java.lang.String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	public java.lang.String getContainerCode() {
		return containerCode;
	}

	public void setContainerCode(java.lang.String containerCode) {
		this.containerCode = containerCode;
	}

	public java.lang.String getContainerDescr() {
		return containerDescr;
	}

	public void setContainerDescr(java.lang.String containerDescr) {
		this.containerDescr = containerDescr;
	}

	public java.lang.String getFamilyCode() {
		return familyCode;
	}

	public void setFamilyCode(java.lang.String familyCode) {
		this.familyCode = familyCode;
	}

	public java.lang.String getFamilyDesc() {
		return familyDesc;
	}

	public void setFamilyDesc(java.lang.String familyDesc) {
		this.familyDesc = familyDesc;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public java.lang.String getUsageCode() {
		return usageCode;
	}

	public void setUsageCode(java.lang.String usageCode) {
		this.usageCode = usageCode;
	}

	public java.lang.String getUsageDesc() {
		return usageDesc;
	}

	public void setUsageDesc(java.lang.String usageDesc) {
		this.usageDesc = usageDesc;
	}

	public java.lang.String getBarcode() {
		return barcode;
	}

	public void setBarcode(java.lang.String barcode) {
		this.barcode = barcode;
	}
	
   public PickupDetail clone() {
  	 return new PickupDetail(categoryCode, categoryDesc, containerCode, containerDescr,
  			familyCode, familyDesc, id, state, usageCode, usageDesc, barcode);
   }
}
