// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package es.sendit2us.wastetracker.client.blackberry.rest;

import net.rim.device.api.util.Persistable;

public class PickupHeader implements Persistable {
	
	public static final long serialVersionUID = -8828636327734194313L;

	protected java.lang.String address;
	protected java.lang.String code;
	protected java.lang.String customerAuthCode;
	protected long deliveryDate;
	protected PickupDetail[] detail;
	protected java.lang.String deviceCode;
	protected int id;
	protected java.lang.String msgError;
	protected java.lang.String name;
	protected long pickupDate;

	public PickupHeader() {
	}

	public PickupHeader(java.lang.String address, java.lang.String code, java.lang.String customerAuthCode,
			long deliveryDate, PickupDetail[] detail, java.lang.String deviceCode, int id, java.lang.String msgError,
			java.lang.String name, long pickupDate) {
		this.address = address;
		this.code = code;
		this.customerAuthCode = customerAuthCode;
		this.deliveryDate = deliveryDate;
		this.detail = detail;
		this.deviceCode = deviceCode;
		this.id = id;
		this.msgError = msgError;
		this.name = name;
		this.pickupDate = pickupDate;
	}

	public java.lang.String getAddress() {
		return address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getCode() {
		return code;
	}

	public void setCode(java.lang.String code) {
		this.code = code;
	}

	public java.lang.String getCustomerAuthCode() {
		return customerAuthCode;
	}

	public void setCustomerAuthCode(java.lang.String customerAuthCode) {
		this.customerAuthCode = customerAuthCode;
	}

	public long getDeliveryDate() {
		return deliveryDate;
	}

	public void setDeliveryDate(long deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public PickupDetail[] getDetail() {
		return detail;
	}

	public void setDetail(PickupDetail[] detail) {
		this.detail = detail;
	}

	public java.lang.String getDeviceCode() {
		return deviceCode;
	}

	public void setDeviceCode(java.lang.String deviceCode) {
		this.deviceCode = deviceCode;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public java.lang.String getMsgError() {
		return msgError;
	}

	public void setMsgError(java.lang.String msgError) {
		this.msgError = msgError;
	}

	public java.lang.String getName() {
		return name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public long getPickupDate() {
		return pickupDate;
	}

	public void setPickupDate(long pickupDate) {
		this.pickupDate = pickupDate;
	}

	public PickupHeader clone() {
		PickupDetail[] newDetail = new PickupDetail[detail.length];
		for (int i = 0; i < detail.length; i++) {
			newDetail[i] = detail[i].clone();
		}
		return new PickupHeader(address, code, customerAuthCode, deliveryDate, newDetail,
				deviceCode, id, msgError, name, pickupDate);
	}
}
