
package es.sendit2us.client.wstest.stubs;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DataManagerImpl", targetNamespace = "http://wastetracker.corecanarias.com/facade")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataManagerImpl {


    /**
     * 
     * @param detail
     * @param ccaa
     * @param phone2
     * @param code
     * @param phone1
     * @param city
     * @param country
     * @param customerAuthCode
     * @param address
     * @param customerCode
     * @param name
     * @param company
     * @param zipCode
     * @return
     *     returns int
     * @throws WasteTrackerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRequest", targetNamespace = "http://wastetracker.corecanarias.com/facade", className = "es.sendit2us.client.wstest.stubs.AddRequest")
    @ResponseWrapper(localName = "addRequestResponse", targetNamespace = "http://wastetracker.corecanarias.com/facade", className = "es.sendit2us.client.wstest.stubs.AddRequestResponse")
    public int addRequest(
        @WebParam(name = "code", targetNamespace = "")
        String code,
        @WebParam(name = "customerCode", targetNamespace = "")
        String customerCode,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "company", targetNamespace = "")
        String company,
        @WebParam(name = "address", targetNamespace = "")
        String address,
        @WebParam(name = "zipCode", targetNamespace = "")
        String zipCode,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "ccaa", targetNamespace = "")
        String ccaa,
        @WebParam(name = "country", targetNamespace = "")
        String country,
        @WebParam(name = "phone1", targetNamespace = "")
        String phone1,
        @WebParam(name = "phone2", targetNamespace = "")
        String phone2,
        @WebParam(name = "customerAuthCode", targetNamespace = "")
        String customerAuthCode,
        @WebParam(name = "detail", targetNamespace = "")
        List<PickupDetail> detail)
        throws WasteTrackerException_Exception
    ;

}
