
package es.sendit2us.client.wstest.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DataManagerImplService", targetNamespace = "http://wastetracker.corecanarias.com/facade", wsdlLocation = "http://wastetracker.corecanarias.com:8080/WasteTracker-WasteTrackerServer/DataManagerImpl?wsdl")
public class DataManagerImplService
    extends Service
{

    private final static URL DATAMANAGERIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.sendit2us.client.wstest.stubs.DataManagerImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.sendit2us.client.wstest.stubs.DataManagerImplService.class.getResource(".");
            url = new URL(baseUrl, "http://wastetracker.corecanarias.com:8080/WasteTracker-WasteTrackerServer/DataManagerImpl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://wastetracker.corecanarias.com:8080/WasteTracker-WasteTrackerServer/DataManagerImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATAMANAGERIMPLSERVICE_WSDL_LOCATION = url;
    }

    public DataManagerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataManagerImplService() {
        super(DATAMANAGERIMPLSERVICE_WSDL_LOCATION, new QName("http://wastetracker.corecanarias.com/facade", "DataManagerImplService"));
    }

    /**
     * 
     * @return
     *     returns DataManagerImpl
     */
    @WebEndpoint(name = "DataManagerImplPort")
    public DataManagerImpl getDataManagerImplPort() {
        return super.getPort(new QName("http://wastetracker.corecanarias.com/facade", "DataManagerImplPort"), DataManagerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataManagerImpl
     */
    @WebEndpoint(name = "DataManagerImplPort")
    public DataManagerImpl getDataManagerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wastetracker.corecanarias.com/facade", "DataManagerImplPort"), DataManagerImpl.class, features);
    }

}
