
package es.sendit2us.client.wstest.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "WasteTrackerException", targetNamespace = "http://wastetracker.corecanarias.com/facade")
public class WasteTrackerException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WasteTrackerException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WasteTrackerException_Exception(String message, WasteTrackerException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WasteTrackerException_Exception(String message, WasteTrackerException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.sendit2us.client.wstest.stubs.WasteTrackerException
     */
    public WasteTrackerException getFaultInfo() {
        return faultInfo;
    }

}
