// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package es.sendit2us.wastetracker.client.blackberry;

import es.sendit2us.wastetracker.client.blackberry.rest.CategoryIncidenceEntity;


public class CategoryIncidenceEntityDecorator extends CategoryIncidenceEntity {

    public CategoryIncidenceEntityDecorator() {
   	 super();
    }
    
    public CategoryIncidenceEntityDecorator(java.lang.String code, java.lang.String description, int id) {
        super(code, description, id);
    }

    public String toString() {
   	return description;
   }
}
